// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbggenpmassgvvhnehgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiZ2dlbnBtYXNzZ3Z2aG5laGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTc5MDEsImV4cCI6MjA2NjU3MzkwMX0.FW7DKxvV4uTfkR49-zQKe9GEKe_z4Sstf7nxKZXVfig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);